# Generated by Django 5.1 on 2024-08-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_profile_of_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='life_events',
            field=models.ManyToManyField(blank=True, related_name='profile', to='APP.lifeevent'),
        ),
    ]
