# Generated by Django 5.1 on 2024-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_post_author_profile_can_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='CIM', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('ES', 'Esemény'), ('HI', 'Hír')], default='HI', max_length=2),
            preserve_default=False,
        ),
    ]
