# Generated by Django 5.1 on 2024-08-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_post_image_post_title_post_type_of_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='lifeevent',
            options={'verbose_name': 'Life Event', 'verbose_name_plural': 'Life Events'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='socialsite',
            options={'verbose_name': 'Social Site', 'verbose_name_plural': 'Social Sites'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'Year', 'verbose_name_plural': 'Years'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(default='https://i.postimg.cc/hvhBb2vp/Group-3.png', max_length=255),
        ),
    ]
